development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fbi_db
  pool: 5
  username: root
  password: password
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  database: fbi_staging
  username: root
  password: root
  host: localhost
